# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - webnet

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - webnet

  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web/web1:/usr/share/nginx/html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web/web2:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet: